# Generated by Django 6.0.3 on 2026-05-18 09:44

import django_pymissive.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0004_missiveproof_alter_missivecampaign_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missive',
            name='attachment_processors',
            field=django_pymissive.fields.JSONField(blank=True, default=list, help_text='Ordered list of processors applied to every attachment\'s bytes right before the missive is handed to the provider. Each processor receives (missive, attachment, content_bytes) and must return new bytes. PDF-only processors (e.g. watermark_pdf_attachments) skip non-PDF attachments. When non-empty, REPLACES the campaign and global defaults (PYMISSIVE_DEFAULT_ATTACHMENT_PROCESSORS). Each entry may be a dotted path string, a [path, kwargs] pair, or a {"processor": path, "kwargs": {...}} dict.', verbose_name='Attachment processors'),
        ),
        migrations.AddField(
            model_name='missive',
            name='body_processors',
            field=django_pymissive.fields.JSONField(blank=True, default=list, help_text='Ordered list of processors applied to compiled subject/body/first_document content. When non-empty, REPLACES the campaign and global defaults (PYMISSIVE_DEFAULT_BODY_PROCESSORS) — make sure to include django_template_processor here if you still want {{ var }} / {% tag %} rendering. Each entry may be a dotted path string, a [path, kwargs] pair, or a {"processor": path, "kwargs": {...}} dict.', verbose_name='Body processors'),
        ),
        migrations.AddField(
            model_name='missive',
            name='first_document_processors',
            field=django_pymissive.fields.JSONField(blank=True, default=list, help_text='Ordered list of processors used to build the first_document PDF (postal/LRE letter). The first processor receives no input and must produce PDF bytes (default: WeasyPrint render of the compiled HTML); subsequent processors receive the previous output and may transform it (watermark, append pages, sign...). When non-empty, REPLACES the campaign and global defaults (PYMISSIVE_DEFAULT_FIRST_DOCUMENT_PROCESSORS) — include django_pymissive.pdf_processors.weasyprint_renderer if you still want the default HTML→PDF rendering. Each entry may be a dotted path string, a [path, kwargs] pair, or a {"processor": path, "kwargs": {...}} dict.', verbose_name='First document PDF processors'),
        ),
        migrations.AddField(
            model_name='missivecampaign',
            name='attachment_processors',
            field=django_pymissive.fields.JSONField(blank=True, default=list, help_text="Ordered list of processors applied to every attachment of missives in this campaign right before sending. Each processor receives (missive, attachment, content_bytes) and returns new bytes. PDF-only processors (e.g. watermark_pdf_attachments) skip non-PDF attachments. When non-empty, REPLACES the global defaults (PYMISSIVE_DEFAULT_ATTACHMENT_PROCESSORS). A missive's own non-empty attachment_processors will in turn override these.", verbose_name='Attachment processors'),
        ),
        migrations.AddField(
            model_name='missivecampaign',
            name='body_processors',
            field=django_pymissive.fields.JSONField(blank=True, default=list, help_text='Ordered list of processors applied to compiled campaign body/first_document content. When non-empty, REPLACES the global defaults (PYMISSIVE_DEFAULT_BODY_PROCESSORS) — make sure to include django_template_processor here if you still want {{ var }} / {% tag %} rendering. A missive\'s own non-empty body_processors will in turn override these. Each entry may be a dotted path string, a [path, kwargs] pair, or a {"processor": path, "kwargs": {...}} dict.', verbose_name='Body processors'),
        ),
        migrations.AddField(
            model_name='missivecampaign',
            name='first_document_processors',
            field=django_pymissive.fields.JSONField(blank=True, default=list, help_text='Ordered list of processors used to build the first_document PDF for missives in this campaign. When non-empty, REPLACES the global defaults (PYMISSIVE_DEFAULT_FIRST_DOCUMENT_PROCESSORS) — include django_pymissive.pdf_processors.weasyprint_renderer as the first entry if you still want the default HTML→PDF rendering. A missive\'s own non-empty first_document_processors will in turn override these. Each entry may be a dotted path string, a [path, kwargs] pair, or a {"processor": path, "kwargs": {...}} dict.', verbose_name='First document PDF processors'),
        ),
    ]
