# Generated by Django 6.0.5 on 2026-05-21 21:23

import django_pymissive.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_pymissive", "0005_missive_attachment_processors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missive",
            name="attachment_processors",
            field=django_pymissive.fields.JSONField(
                blank=True,
                default=list,
                help_text='Ordered list of processors. When non-empty, REPLACES inherited defaults. Runtime resolution (first non-empty wins): this object\'s value, then its campaign\'s value (when this is a missive linked to a campaign), then the global setting. Each entry may be a dotted-path string, a ``[path, kwargs]`` pair, or a ``{"processor": path, "kwargs": {...}}`` dict. When overriding the body chain, include ``django_pymissive.processors.body.django_template.django_template_processor`` if you still want ``{{ var }}`` / ``{% tag %}`` rendering; when overriding the first_document chain, include ``django_pymissive.processors.pdf.weasyprint_renderer.weasyprint_renderer`` (or your own renderer) as the first entry.',
                verbose_name="Attachment processors",
            ),
        ),
        migrations.AlterField(
            model_name="missive",
            name="body_processors",
            field=django_pymissive.fields.JSONField(
                blank=True,
                default=list,
                help_text='Ordered list of processors. When non-empty, REPLACES inherited defaults. Runtime resolution (first non-empty wins): this object\'s value, then its campaign\'s value (when this is a missive linked to a campaign), then the global setting. Each entry may be a dotted-path string, a ``[path, kwargs]`` pair, or a ``{"processor": path, "kwargs": {...}}`` dict. When overriding the body chain, include ``django_pymissive.processors.body.django_template.django_template_processor`` if you still want ``{{ var }}`` / ``{% tag %}`` rendering; when overriding the first_document chain, include ``django_pymissive.processors.pdf.weasyprint_renderer.weasyprint_renderer`` (or your own renderer) as the first entry.',
                verbose_name="Body processors",
            ),
        ),
        migrations.AlterField(
            model_name="missive",
            name="first_document_processors",
            field=django_pymissive.fields.JSONField(
                blank=True,
                default=list,
                help_text='Ordered list of processors. When non-empty, REPLACES inherited defaults. Runtime resolution (first non-empty wins): this object\'s value, then its campaign\'s value (when this is a missive linked to a campaign), then the global setting. Each entry may be a dotted-path string, a ``[path, kwargs]`` pair, or a ``{"processor": path, "kwargs": {...}}`` dict. When overriding the body chain, include ``django_pymissive.processors.body.django_template.django_template_processor`` if you still want ``{{ var }}`` / ``{% tag %}`` rendering; when overriding the first_document chain, include ``django_pymissive.processors.pdf.weasyprint_renderer.weasyprint_renderer`` (or your own renderer) as the first entry.',
                verbose_name="First document PDF processors",
            ),
        ),
        migrations.AlterField(
            model_name="missive",
            name="subject",
            field=models.TextField(
                blank=True,
                help_text="Subject line (for email, SMS, etc.)",
                null=True,
                verbose_name="Subject",
            ),
        ),
        migrations.AlterField(
            model_name="missivecampaign",
            name="attachment_processors",
            field=django_pymissive.fields.JSONField(
                blank=True,
                default=list,
                help_text='Ordered list of processors. When non-empty, REPLACES inherited defaults. Runtime resolution (first non-empty wins): this object\'s value, then its campaign\'s value (when this is a missive linked to a campaign), then the global setting. Each entry may be a dotted-path string, a ``[path, kwargs]`` pair, or a ``{"processor": path, "kwargs": {...}}`` dict. When overriding the body chain, include ``django_pymissive.processors.body.django_template.django_template_processor`` if you still want ``{{ var }}`` / ``{% tag %}`` rendering; when overriding the first_document chain, include ``django_pymissive.processors.pdf.weasyprint_renderer.weasyprint_renderer`` (or your own renderer) as the first entry.',
                verbose_name="Attachment processors",
            ),
        ),
        migrations.AlterField(
            model_name="missivecampaign",
            name="body_processors",
            field=django_pymissive.fields.JSONField(
                blank=True,
                default=list,
                help_text='Ordered list of processors. When non-empty, REPLACES inherited defaults. Runtime resolution (first non-empty wins): this object\'s value, then its campaign\'s value (when this is a missive linked to a campaign), then the global setting. Each entry may be a dotted-path string, a ``[path, kwargs]`` pair, or a ``{"processor": path, "kwargs": {...}}`` dict. When overriding the body chain, include ``django_pymissive.processors.body.django_template.django_template_processor`` if you still want ``{{ var }}`` / ``{% tag %}`` rendering; when overriding the first_document chain, include ``django_pymissive.processors.pdf.weasyprint_renderer.weasyprint_renderer`` (or your own renderer) as the first entry.',
                verbose_name="Body processors",
            ),
        ),
        migrations.AlterField(
            model_name="missivecampaign",
            name="first_document_processors",
            field=django_pymissive.fields.JSONField(
                blank=True,
                default=list,
                help_text='Ordered list of processors. When non-empty, REPLACES inherited defaults. Runtime resolution (first non-empty wins): this object\'s value, then its campaign\'s value (when this is a missive linked to a campaign), then the global setting. Each entry may be a dotted-path string, a ``[path, kwargs]`` pair, or a ``{"processor": path, "kwargs": {...}}`` dict. When overriding the body chain, include ``django_pymissive.processors.body.django_template.django_template_processor`` if you still want ``{{ var }}`` / ``{% tag %}`` rendering; when overriding the first_document chain, include ``django_pymissive.processors.pdf.weasyprint_renderer.weasyprint_renderer`` (or your own renderer) as the first entry.',
                verbose_name="First document PDF processors",
            ),
        ),
        migrations.AlterField(
            model_name="missivecampaign",
            name="subject",
            field=models.TextField(
                help_text="Campaign subject", verbose_name="Subject"
            ),
        ),
    ]
