# Generated by Django 6.0.5 on 2026-05-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_pymissive", "0006_alter_missive_attachment_processors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missive",
            name="missive_type",
            field=models.CharField(
                choices=[
                    ("lre", "Electronic registered letter (LRE)"),
                    ("hand_delivery", "Hand delivery"),
                    ("ere", "Electronic registered email (ERE)"),
                    ("email", "Email"),
                    ("email_marketing", "Marketing email"),
                    ("sms", "SMS"),
                    ("rcs", "RCS (Rich SMS)"),
                    ("voice_call", "Automated voice call"),
                    ("notification", "In-app notification"),
                    ("push_notification", "Mobile push notification"),
                    ("branded", "Branded App messaging (WhatsApp, Slack, etc.)"),
                ],
                help_text="Type of missive (email, sms, lre, ere, etc.)",
                max_length=50,
                verbose_name="Missive Type",
            ),
        ),
        migrations.AlterField(
            model_name="missiveconfig",
            name="missive_type",
            field=models.CharField(
                choices=[
                    ("lre", "Electronic registered letter (LRE)"),
                    ("hand_delivery", "Hand delivery"),
                    ("ere", "Electronic registered email (ERE)"),
                    ("email", "Email"),
                    ("email_marketing", "Marketing email"),
                    ("sms", "SMS"),
                    ("rcs", "RCS (Rich SMS)"),
                    ("voice_call", "Automated voice call"),
                    ("notification", "In-app notification"),
                    ("push_notification", "Mobile push notification"),
                    ("branded", "Branded App messaging (WhatsApp, Slack, etc.)"),
                ],
                help_text="Type of missive (email, sms, postal, etc.)",
                max_length=50,
                unique=True,
                verbose_name="Missive type",
            ),
        ),
    ]
