# Generated by Django 6.0.3 on 2026-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sample.pdf', max_length=200)),
                ('fixture_path', models.CharField(blank=True, default='', help_text='Optional absolute path to a PDF on disk. Defaults to tests/pdf_sample_1mb.pdf when blank.', max_length=500)),
            ],
            options={
                'verbose_name': 'PDF document (test fixture)',
            },
        ),
    ]
