# Generated by Django 6.0.3 on 2026-05-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Optional publication date (used to test datetime serialization in context).', null=True),
        ),
    ]
